[package]
name = "ckb-lib-pw-lock"
version = "0.1.0"
authors = ["zero.qn <zero.qn@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-std = "0.7"

[build-dependencies]
blake2b-rs = "0.2"
